region                = "us-east-1"
source_bucket_name    = "my-source-bucket-unique"
destination_bucket_name = "my-destination-bucket-unique"
replication_role_name = "s3-replication-role"
aws_account_id        = "123456789012"